# Generated by Django 4.2.9 on 2024-07-26 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0001_initial"),
        ("article", "0002_imagearticle_articlestamp_articlesentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCircleAssociate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.articles",
                    ),
                ),
                (
                    "Circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="circle.circle"
                    ),
                ),
            ],
        ),
    ]
