# Generated by Django 4.2.9 on 2024-08-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_articlecircleassociate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecircleassociate",
            old_name="Article",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="articlecircleassociate",
            old_name="Circle",
            new_name="circle",
        ),
    ]
