# Generated by Django 4.2.9 on 2024-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
